### ISSUE TITLE
Armory Updating

### ISSUE THREAD

**Issue by dj-riff** [Twintop/beotorch-issues#20]
I know we spoke about this a bit yesterday, but i checked my armory and it is currently showing me as shadow in shadow gear, however anytime i try and load my priest it has me listed as holy.

**Comment by Twintop** [comment]
Will hopefully have a workaround (via a new feature) for this sometime this weekend.

**Comment by Twintop** [comment]
Thinking about this a little more, I'm not sure if (because of how Artifacts are tied to specs) my original plan of letting people choose any spec they can play will be a good solution. If you try to switch from Fire to Frost for a sim and you have the Fire artifact still, that'll lead to bad (impossible) information. Going to have to look at other ways to avoid this issue.

**Comment by Twintop** [comment]
Fixed in next deployment.
