### ISSUE TITLE
Minor Queue Limit Adjustment

### ISSUE THREAD

**Issue by Bellapal** [Twintop/beotorch-issues#22]
I'm wondering if it would be possible to raise the queue limit from 10 to 12. The reason is that when I'm trying to run any type of simulations with 2 bosses and comparing talents for a given tier, it uses 6 spots. The screen won't refresh when the simulation finishes, so I have to leave, wait, and then eventually come back and que up my second run. And if I set anything up ahead of time, it's lost. Either because I left the screen or refreshed. If the queue size was 12, I could work on setting up the next run after submitting the first and not lose anything. It's not a big deal, just a minor annoyance. Running multiple talent sims with 1 boss goes much smoother because the queue size is large enough that it doesn't lock me out of the second set. Thanks for considering this. Really loving this site.

**Comment by Twintop** [comment]
This is a bug, it should cost 5 spots for a 10k iteration simulation with stat weights (so you can do a 2 talent comparison with weights). Will fix.

**Comment by Bellapal** [comment]
I don't think it's a bug. The number of spots it takes up to do a 10K iteration for 3 talent comparisons for 2 bosses is 6 spots. Then you have to wait to do a second one of the same type cause there are only 4 spots left.

**Comment by Twintop** [comment]
OK, I was able to look in to this more and everything is correct.

It costs 1 slot per specset. The design is that you can do a comparison simulation between two specs with 1 boss with stat weights (2 \* 1 \* 5 = 10), or, one spec with two bosses and stat weights (1 \* 2 \* 5 = 10).

The design behind this is completely intentional: I don't want to give users the ability to spam the queue with simulations at peak hours, causing a slowdown for everyone else as a result. You're still able to create a simulation with the maximum settings allowed for a single spec, i.e., no restrictions on a single simulation. If you want to do more, you'll just have to be patient and wait. :)

While I wouldn't recommend doing a simulation below 10k iterations, if you lower the number of iterations on a talent comparison/multiple boss/stat weight simulation, the queue cost will go down. You _could_ queue up a 10k iteration 3 talentset 2 target sim for 6, and then queue up another at lower iterations that would cost 4.

There is one other way to increase what's available for simulation settings right now. If you are a HowToPriest donor you gain access to a few more features, including:
- making simulations hidden from the public lists
- a maximum of 50 reports before autoarchiving occurs (up from 25)
- 45 days before reports are archived (up from 15 days)
- 25k iterations max (up from 10k iterations)
- simulation length between 60 - 900 seconds (up from 180 - 600 seconds)
- up to 4 target simulations (up from 2)
- 6 talent comparisons per sim (up from 3)

I'm also planning on doing a Patreon at some point (to help pay my power bill for running these nodes to do that computation, not to actually turn a profit) that will have higher/better perks than H2P Donors receive. No ETA on that yet, though.

**Comment by Twintop** [comment]
Also, because it is important to call out in the H2P Donor level, you also have a maximum queue size of 25, up from 10, so you can actually use the higher levels of everything else available. Something similar will exist for Patreon.
