### ISSUE TITLE
Character rundown via Battletag/Battle.net link to sort realms

### ISSUE THREAD

**Issue by Duskyqt** [Twintop/beotorch-issues#8]
It might be a nice addition to add a battle.net link to your website to make the character selection quicker and easier to manage if you have many characters across many servers, maybe a way to " Favourite " realms for quick selection as well could be useful if implementing battle.net integration is more of a headache than it's worth.

TL;DR

Battle.net Character Integration via Battletag or APi.

Favouriting realms for quick selection in dropdown menu. 

(I don't know how to add labels D:)

**Comment by Twintop** [comment]
I do want to add OAuth so your list of characters gets imported automatically. That is probably a ways off because, while important for sure, there are other features I think will be more useful in the nearer term.

In the meantime, though, I'm toying with some ways to make it easier to get at your frequently used Character/Server combos. I'll keep this bug updated as I try things out or come up with concepts. Thanks!

**Comment by Twintop** [comment]
Not the exact functionality you described but a stopgap until I can get around to OAuth. I'll probably extend this to let you pick what characters you want in the list at some point.
